### ISSUE TITLE
Include what is working in README

### ISSUE THREAD

**Issue by ryanleesipes** [ubuntu-touch-oneplus-one/ubuntu-touch-for-oneplus-one#10]
Would be really helpful to include what is currently working in the README so that people can track progress.

**Comment by kokoye2007** [comment]
NOT Working:
GSM Network
Camera

**Comment by msri3here** [comment]
is Wi Fi working now?

**Comment by kokoye2007** [comment]
sorry. wifi is also WIP.
not working

On Tue, Mar 10, 2015 at 6:32 PM, msri3here <notifications@github.com> wrote:

> is Wi Fi working now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ubuntu-touch-oneplus-one/ubuntu-touch-for-oneplus-one/issues/10#issuecomment-78040438>
> .
>



-- 
*Ko Ko Ye`*

+95 973147907
+95 94500 22022

kokoye2007@gmail.com
kokoye2007@ubuntu.com

skype: kokoye2007
jit.si: kokoye2007

http://ubuntu-mm.net
http://wiki.ubuntu.com/kokoye2007
http://wiki.ubuntu.com/MyanmarTeam
http://loco.ubuntu.com/teams/ubuntu-mm

**Comment by ryanleesipes** [comment]
Thank you!
