### ISSUE TITLE
Bootloop after install

### ISSUE THREAD

**Issue by eeegadds** [ubuntu-touch-oneplus-one/ubuntu-touch-for-oneplus-one#4]
Followed video tutorial you posted everything went fine until it rebooted then it just bootloops.

**Comment by robbyf** [comment]
You might need to flash CM 12 first, it updates bootloader firmware.

**Comment by eeegadds** [comment]
I had cm 12 flashed wiped in twrp . It bootlooped after using rootstock to install.

**Comment by dreamdickey** [comment]
I have the same issue with you,and my last system is cm12,too...Maybe should flash cm11 first?

**Comment by Zeero1778** [comment]
I had CM11S 05Q and it had no bootloops.

**Comment by eeegadds** [comment]
mariogrip said: ↑
For some reason you device is adding "console=ttyHSL0,115200,n8 " to the console line by it self, in order ubuntu touch to boot, you need "console=tty0". I guess it's the bootloader that is passing this kernel value, try flashing stock rom.
You can try this boot.img (https://dl.dropboxusercontent.com/u/56653875/ubuntu/t2/boot2.img) that has console=tty0 set in the kernel cmdline. This worked.
